# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 08:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_auto_20180416_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 16, 8, 9, 46, 100000, tzinfo=utc)),
        ),
    ]
