# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 08:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_auto_20180416_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 16, 8, 12, 5, 780000, tzinfo=utc)),
        ),
    ]
